//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guest()
        {
            this.Histories = new HashSet<History>();
        }
    
        [Required(ErrorMessage = "Guest must have some form of ID")]
        public string guestID { get; set; }

        public bool prohibited { get; set; }
        public Nullable<System.DateTime> prohibitedDate { get; set; }
        public string notes { get; set; }
        public string identityType { get; set; }
        public bool isStudent { get; set; }

        [Required(ErrorMessage = "Please enter the guest's first name")]
        public string firstName { get; set; }

        [Required(ErrorMessage = "Please enter the guest's last name")]
        public string lastName { get; set; }

        public bool gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
    }
}
