//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class History
    {
        [Key]
        public int transactionID { get; set; }

        public string guestID { get; set; }
        public int hostID { get; set; }
        public string building { get; set; }
        public string bedspace { get; set; }
        public string updatedBy { get; set; }
        public bool overnight { get; set; }

        [Column(TypeName = "datetime2")]
        public System.DateTime inTime { get; set; }

        public Nullable<System.DateTime> outTime { get; set; }
        public Nullable<System.DateTime> expired { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Resident Resident { get; set; }

        public object grabActives() {
            //Grab a resident's three active guests
            using (masterEntities db = new masterEntities()) {
                List<History> details = db.Histories.Where(x => x.hostID == hostID && x.outTime == null).ToList();
                foreach (var row in details) {
                    Guest.guestID = row.Guest.guestID;
                }
                return details;
            }
        }

    }
}
