//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Resident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resident()
        {
            this.Histories = new HashSet<History>();
        }

        [Required(ErrorMessage = "Resident must have a Student ID to sign in a guest")]
        public int studentID { get; set; }

        public string firstName { get; set; }
        public string lastName { get; set; }
        public string building { get; set; }
        public string room { get; set; }
        public System.DateTime moveInDate { get; set; }
        public Nullable<System.DateTime> moveOutDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
        public virtual ZipCard ZipCard { get; set; }
    }
}
